@startuml Future state
    entity User {
        * id : int <<generated>>
    }

    entity UserAuth {
        * user_auth_source_id : int <<FK>>
        * user_id : int <<FK>>
        * auth_info : text
    }

    entity UserAuthSource {
        * id : int <<generated>>
        * name : varchar
    }

    entity Map {
        * id : int <<generated>>
        * map_id : varchar
        * title : varchar
        * artist : varchar
        * mapper : varchar
    }

    entity Tournament {
        * id : int <<generated>>
        * state : enum<stopped|running|paused|done>
        * tournament_type : int <<FK>>
        * max_songs : int
        * stop_recording_after_max : bool
        * user_id : int <<FK>>
    }

    entity TournamentType {
        * id : int <<generated>>
        * name : varchar
    }

    entity PlayInstance {
        * id : int <<generated>>
        * map_id : int <<FK>>
        * room_name : string
        * timestamp : timestamp
        * tournament_id : int <<FK>>
    }

    entity ScoreSubmission {
        * id : int <<generated>>
        * user_id : int <<FK>>
        * submitted_on : timestamp
        * play_instance_id : int <<FK>>
    }

    entity Score {
        * id : int <<generated>>
        * score_submission_id : int <<FK>>
        * player_name : varchar
        * score : int
        * total_notes : int
        * total_notes_hit : int
        * perfect_hits : int
        * good_hits : int
        * poor_hits : int
        * longest_streak : int
        * max_multiplier : int
        * specials_hit : int
        * specials_total : int
    }

    UserAuthSource }|-- UserAuth
    User }|-- UserAuth

    Score }|-- ScoreSubmission
    ScoreSubmission }|-- PlayInstance
    ScoreSubmission }|-- User
    PlayInstance }|-- Map
    PlayInstance }|-- Tournament
    Tournament }|-- TournamentType
    Tournament }|-- User

@enduml

@startuml Initial MVP
    entity SynthMap {
        * id : int <<generated>>
        * map_id : varchar
        * title : varchar
        * artist : varchar
        * mapper : varchar
    }

    entity PlayInstance {
        * id : int <<generated>>
        * map_id : int <<FK>>
        * timestamp : timestamp
        room_id : string
    }

    note right of PlayInstance::room_id
        Unique multiplayer room id, if available
        so multiple submissions can be aggregated
    endnote

    entity ScoreSubmission {
        * id : int <<generated>>
        * submitter : varchar
        * submitted_on : timestamp
        * play_instance_id : int <<FK>>
    }

    entity Score {
        * id : int <<generated>>
        * score_submission_id : int <<FK>>
        * player_name : varchar
        * score : int
        * total_notes : int
        * total_notes_hit : int
        * perfect_hits : int
        * good_hits : int
        * poor_hits : int
        * longest_streak : int
        * max_multiplier : int
        * specials_hit : int
        * specials_total : int
    }

    Score }|-- ScoreSubmission
    ScoreSubmission }|-- PlayInstance
    PlayInstance }|-- SynthMap

@enduml